"""add content_simplified to poems

Revision ID: 7c21ad447e9c
Revises: d0e52d00bc0b
Create Date: 2026-04-27 20:55:19.756355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c21ad447e9c'
down_revision: Union[str, None] = 'd0e52d00bc0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poems', sa.Column('content_simplified', sa.Text(), nullable=False,server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poems', 'content_simplified')
    # ### end Alembic commands ###
